### ISSUE TITLE
ajouter un numero dans chaque pieces, au centre, noir graffiti pour facilité la navigation

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/UnityStation-Tutorial_module#65]

**Comment by HenriquePEIXRIB** [comment]
![image](https://user-images.githubusercontent.com/99975494/203571396-e0414e09-0385-4edb-93af-dabed3c7c870.png)

![image](https://user-images.githubusercontent.com/99975494/203571695-3faf5d79-a06b-414f-97e0-32fe5c070d2a.png)

**Comment by HenriquePEIXRIB** [comment]
Image numérotation + trou boucher

**Comment by HenriquePEIXRIB** [comment]
https://github.com/Unitystation-fork/UnityStation-Tutorial_module/tree/HenriquePEIXRIB-patch-1

**Comment by Fr-Dae** [comment]
![Image](https://user-images.githubusercontent.com/23202421/203782377-050a439b-4aa0-42bf-b8c2-f45ffc654e5a.png)
